### PR TITLE
w01d05 Homework Ketchup

### PR DESCRIPTION
**Pull request by smaupin**
comfort: 3
completeness: 3

Added tic-tac-toe game. Instituted more organized folder structure so I can know what goes where. Catching up on other commits and homework during the rest of today and tomorrow before class on Tuesday.

### CODE REVIEW

**Comment by smaupin** [comment]
w02d02

completeness: 5
comfort: 5

I have been having a really hard time wrapping my head around using APIs, this helps to review them and helps me understand better now. (as it should since I've been working with APIs for close to a week now, but I am starting to get familiar with them at last, I feel.)

**Comment by smaupin** [comment]
Also, when making these simple html files that contain answers to homework questions, Do I need to do the full HTML format? Is it better to submit them without it? Just checking.

**Comment by tgaff** [comment]
@smaupin What do you mean by full html format?  It should be valid HTML.  I think some of the homework (last night's) allowed a .md file too.  (look up markdown)

**Comment by tgaff** [comment]
@smaupin we need a .gitignore... you are adding .DS_Store files which cause merge conflicts for other students.  Please copy the .gitignore from this repository and put it in yours, then commit it and delete the .DS_Store file from your repo.

**Comment by tgaff** [comment]
@smaupin  do you have yesterday's homework too?

**Comment by smaupin** [comment]
@tgaff by full html I mean with a head and body and tags and everything that would make it load on a browser. Like I would put in <p> tags and <br> in the homework instead of just hitting return and starting on a new line, sans formatting. 

also - I dont understand your comment about gitignore and the DS_store files. Could i get your help sometime to guide me or walk me through it. I don't want to end up messing up my git further, which I feel is totally possible if I try to do it on my own.

and no, I havent been able to do yesterday's homework yet. I finished the reading, but today's and yesterday's material has thusfar made very little sense in my brain. I am trying though.

**Pull request merged**
