### PR TITLE
w01d04

### PR DESCRIPTION
**Pull request by jeehyekim**
comfort: 3
completeness: 5

Since we did pair programming for the exercises, Vince and I were able to get through most of the challenges fairly quickly. We did the main challenges and did not do the bonus challenges. However, we had a really hard time with the last one and were not able to figure out how to get it to work. The solution: Solutions. :P 

On Wednesday, I felt like I was getting a good grasp on a lot of what we learned but I realize there's a lot of stuff I still need to review. Specifically CSS and selectors.

Weekend plan: 
- review CSS and selectors
- review javascript + jquery
- try to do the bonus challenges and exercises I was not able to complete while in class.

### CODE REVIEW

**Comment by jeehyekim** [comment]
w01 tictactoe weekend lab 

comfort: 4
completeness: 5

I was able to get most of the project down. Each time "Reset" is selected, "New Game" flashes. At the top, it switches from displaying "Player 1" and "Player 2." The marks switch from X and O. 

The problem that I'm running into is getting it to display the winner. I tried using an if, else if, else statement. But everytime I try running it, it doesn't work :( .

**Comment by jeehyekim** [comment]
w02d01 OOP.html

comfort:3
completeness:3

Even with the reading, I find myself still confused about what I'm reading. Regarding the homework, I left the questions blank as I'm not sure what exactly I'm confused about and what questions I should be asking.

**Comment by jeehyekim** [comment]
w02d03 - Google Maps API

comfort: 4
completeness: 5

Today was a good day compared to the last couple days. I feel that what we've been learning this week is starting to gel together today.

**Comment by tgaff** [comment]
@jeehyekim thank you so much for putting in PR comments for each day!

**Comment by tgaff** [comment]
@jeehyekim we need to add a .gitignore file to your repo so that .DS_Store doesn't show up.  Could you copy the one in this repo and add it to yours?

**Pull request merged**
